[package]
name = "block-alloc"
version = "0.1.0"
authors = ["budde25 <budde25@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.3"
bitflags = "1.3.2"
sptr = "0.3.2"
